"""add can_manage_notifications permission

Revision ID: d83b36d7a9eb
Revises: bb68450778d5
Create Date: 2026-04-26 13:47:12.781952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83b36d7a9eb'
down_revision = 'bb68450778d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_manage_notifications', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('can_manage_notifications')

    # ### end Alembic commands ###
